version: '3.7'

services: 
  gateway:
    build:
      context: ../..
      dockerfile: build/package/gateway/Dockerfile
    image: qultist/ql-gateway:0.1
    ports: 
      - '8080:8080'
  grpc-service:
    build:
      context: ../..
      dockerfile: build/package/grpc-service/Dockerfile
    image: qultist/ql-grpc-service:0.1
    depends_on:
      - redis
  http-service:
    image: qultist/ql-http-service:0.1
    ports:
      - '8081:8080'
  redis:
    image: redis:5.0-alpine
    ports:
      - '6379:6379'