version: '3.7'

services: 
  gateway:
    build:
      context: ../..
      dockerfile: build/package/gateway/Dockerfile
    image: qultist/ql-gateway:0.1
    ports: 
      - '8080:8080'
  grpc-service:
    build:
      context: ../..
      dockerfile: build/package/grpc-service/Dockerfile
    image: qultist/ql-grpc-service:0.1
    depends_on:
      - redis
  kafka-service:
    build:
      context: ../..
      dockerfile: build/package/kafka-service/Dockerfile
    image: qultist/ql-kafka-service:0.1
    entrypoint: ./docker-entrypoint.sh
    depends_on:
      - redis
      - ql-zookeper-client
  http-service:
    image: qultist/ql-http-service:0.1
    ports:
      - '8081:8080'
  redis:
    image: redis:5.0-alpine
    ports:
      - '6379:6379'
  ql-zookeper-client:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  ql-kafka-bootstrap:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ql-kafka-bootstrap
      KAFKA_CREATE_TOPICS: "quests:1:1"
      KAFKA_ZOOKEEPER_CONNECT: ql-zookeper-client:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock